### ISSUE TITLE
Hyperpixel not working

### ISSUE THREAD

**Issue by drewcovi** [balena-os/balena-raspberrypi#221]
Any help here would be immensely appreciated... I'm attempting to get the Hyperpixel up and running on the latest ResinOS.

I've seen others have had success, but I'm unable to sort out what to change. I've provided the overlay in the boot folder, but I'm unable to get anything to display when setting display_default_lcd=1

I've attached my custom config variables for reference.
<img width="1311" alt="screen shot 2018-08-07 at 11 49 08 am" src="https://user-images.githubusercontent.com/400278/43790333-ed4b2568-9a37-11e8-9260-69c535d4f5dd.png">

**Comment by drewcovi** [comment]
The resulting config.txt after syncing with resin.io

```
disable_splash=0
display_default_lcd=1
display_rotate=2
dpi_group=2
dpi_mode=87
dpi_output_format=0x6f016
dtparam=audio=on
dtparam=i2c_arm=off
dtparam=spi=off
enable_dpi_lcd=1
framebuffer_height=480
framebuffer_width=800
gpu_mem_1024=512
hdmi_timings=800 0 50 20 50 480 1 3 2 3 0 0 0 60 0 32000000 6
overscan_bottom=0
overscan_left=0
overscan_right=0
overscan_top=0
```

**Comment by drewcovi** [comment]
[    0.000000] PID hash table entries: 2048 (order: 1, 8192 bytes)
[    0.000000] Dentry cache hash table entries: 65536 (order: 6, 262144 bytes)
[    0.000000] Inode-cache hash table entries: 32768 (order: 5, 131072 bytes)
[    0.000000] Memory: 489860K/524288K available (8192K kernel code, 598K rwdata, 2264K rodata, 8192K init, 721K bss, 26236K reserved,8192K cma-reserved)
[    0.000000] Virtual kernel memory layout:
[    0.000000] SLUB: HWalign=64, Order=0-3, MinObjects=0, CPUs=4, Nodes=1
[    0.000000] ftrace: allocating 27776 entries in 82 pages
[    0.000000] Hierarchical RCU implementation.
[    0.000000] NR_IRQS: 16, nr_irqs: 16, preallocated irqs: 16
[    0.000000] arch_timer: cp15 timer(s) running at 19.20MHz (phys).
[    0.000000] clocksource: arch_sys_counter: mask: 0xffffffffffffff max_cycles: 0x46d987e47, max_idle_ns: 440795202767 ns
[    0.000007] sched_clock: 56 bits at 19MHz, resolution 52ns, wraps every 4398046511078ns
[    0.000021] Switching to timer-based delay loop, resolution 52ns
[    0.000269] Console: colour dummy device 80x30
[    0.000300] Calibrating delay loop (skipped), value calculated using timer frequency.. 38.40 BogoMIPS (lpj=192000)
[    0.000318] pid_max: default: 32768 minimum: 301
[    0.000631] Mount-cache hash table entries: 1024 (order: 0, 4096 bytes)
[    0.000646] Mountpoint-cache hash table entries: 1024 (order: 0, 4096 bytes)
[    0.001491] CPU: Testing write buffer coherency: ok
[    0.001904] CPU0: thread -1, cpu 0, socket 0, mpidr 80000000
[    0.002294] Setting up static identity map for 0x100000 - 0x10003c
[    0.002415] Hierarchical SRCU implementation.
[    0.003055] smp: Bringing up secondary CPUs ...
[    0.003757] CPU1: thread -1, cpu 1, socket 0, mpidr 80000001
[    0.004508] CPU2: thread -1, cpu 2, socket 0, mpidr 80000002
[    0.005244] CPU3: thread -1, cpu 3, socket 0, mpidr 80000003
[    0.005351] smp: Brought up 1 node, 4 CPUs
[    0.005375] SMP: Total of 4 processors activated (153.60 BogoMIPS).
[    0.005383] CPU: All CPU(s) started in HYP mode.
[    0.005391] CPU: Virtualization extensions available.
[    0.006138] devtmpfs: initialized
[    0.016322] VFP support v0.3: implementor 41 architecture 3 part 40 variant 3 rev 4
[    0.016536] clocksource: jiffies: mask: 0xffffffff max_cycles: 0xffffffff, max_idle_ns: 19112604462750000 ns
[    0.016558] futex hash table entries: 1024 (order: 4, 65536 bytes)
[    0.017135] pinctrl core: initialized pinctrl subsystem
[    0.017886] NET: Registered protocol family 16
[    0.020381] DMA: preallocated 1024 KiB pool for atomic coherent allocations
[    0.024931] hw-breakpoint: found 5 (+1 reserved) breakpoint and 4 watchpoint registers.
[    0.024944] hw-breakpoint: maximum watchpoint size is 8 bytes.
[    0.025153] Serial: AMBA PL011 UART driver
[    0.026952] bcm2835-mbox 3f00b880.mailbox: mailbox enabled
[    0.027408] uart-pl011 3f201000.serial: could not find pctldev for node /soc/gpio@7e200000/uart0_pins, deferring probe
[    0.058278] bcm2835-dma 3f007000.dma: DMA legacy API manager at a0813000, dmachans=0x1
[    0.059665] SCSI subsystem initialized
[    0.059888] usbcore: registered new interface driver usbfs
[    0.059952] usbcore: registered new interface driver hub
[    0.060190] usbcore: registered new device driver usb
[    0.070082] raspberrypi-firmware soc:firmware: Attached to firmware from 2018-04-16 18:16
[    0.071300] clocksource: Switched to clocksource arch_sys_counter
[    0.152082] VFS: Disk quotas dquot_6.6.0
[    0.152172] VFS: Dquot-cache hash table entries: 1024 (order 0, 4096 bytes)
[    0.152359] FS-Cache: Loaded
[    0.152560] CacheFiles: Loaded
[    0.161433] NET: Registered protocol family 2
[    0.162147] TCP established hash table entries: 4096 (order: 2, 16384 bytes)
[    0.162213] TCP bind hash table entries: 4096 (order: 3, 32768 bytes)
[    0.162313] TCP: Hash tables configured (established 4096 bind 4096)
[    0.162417] UDP hash table entries: 256 (order: 1, 8192 bytes)
[    0.162449] UDP-Lite hash table entries: 256 (order: 1, 8192 bytes)
[    0.162662] NET: Registered protocol family 1
[    0.163115] RPC: Registered named UNIX socket transport module.
[    0.163126] RPC: Registered udp transport module.
[    0.163135] RPC: Registered tcp transport module.
[    0.163143] RPC: Registered tcp NFSv4.1 backchannel transport module.
[    0.221089] hw perfevents: enabled with armv7_cortex_a7 PMU driver, 7 counters available
[    0.224252] workingset: timestamp_bits=14 max_order=17 bucket_order=3
[    0.231923] squashfs: version 4.0 (2009/01/31) Phillip Lougher
[    0.232205] FS-Cache: Netfs 'nfs' registered for caching
[    0.232808] NFS: Registering the id_resolver key type
[    0.232845] Key type id_resolver registered
[    0.232855] Key type id_legacy registered
[    0.232874] nfs4filelayout_init: NFSv4 File Layout Driver Registering...
[    0.234072] aufs 4.14-20180409
[    0.235251] Block layer SCSI generic (bsg) driver version 0.4 loaded (major 251)
[    0.235376] io scheduler noop registered
[    0.235387] io scheduler deadline registered
[    0.235661] io scheduler cfq registered (default)
[    0.235672] io scheduler mq-deadline registered
[    0.235682] io scheduler kyber registered
[    0.238412] BCM2708FB: allocated DMA memory df510000
[    0.238443] BCM2708FB: allocated DMA channel 0 @ a0813000
[    0.248845] Console: switching to colour frame buffer device 100x30
[    0.256074] bcm2835-rng 3f104000.rng: hwrng registered
[    0.256209] vc-mem: phys_addr:0x00000000 mem_base=0x3ec00000 mem_size:0x40000000(1024 MiB)
[    0.256663] vc-sm: Videocore shared memory driver
[    0.256940] gpiomem-bcm2835 3f200000.gpiomem: Initialised: Registers at 0x3f200000
[    0.266515] brd: module loaded
[    0.275175] loop: module loaded
[    0.275195] Loading iSCSI transport class v2.0-870.
[    0.275858] libphy: Fixed MDIO Bus: probed
[    0.275899] tun: Universal TUN/TAP device driver, 1.6
[    0.276117] usbcore: registered new interface driver lan78xx
[    0.276175] usbcore: registered new interface driver smsc95xx
[    0.276194] dwc_otg: version 3.00a 10-AUG-2012 (platform bus)
[    0.504282] Core Release: 2.80a
[    0.504296] Setting default values for core params
[    0.504325] Finished setting default values for core params
[    0.704581] Using Buffer DMA mode
[    0.704592] Periodic Transfer Interrupt Enhancement - disabled
[    0.704601] Multiprocessor Interrupt Enhancement - disabled
[    0.704612] OTG VER PARAM: 0, OTG VER FLAG: 0
[    0.704627] Dedicated Tx FIFOs mode
[    0.705025] WARN::dwc_otg_hcd_init:1046: FIQ DMA bounce buffers: virt = 0x9f504000 dma = 0xdf504000 len=9024
[    0.705055] FIQ FSM acceleration enabled for :
[    0.705078] dwc_otg: Microframe scheduler enabled
[    0.705123] WARN::hcd_init_fiq:459: FIQ on core 1 at 0x8064f158
[    0.705138] WARN::hcd_init_fiq:460: FIQ ASM at 0x8064f4b4 length 36
[    0.705153] WARN::hcd_init_fiq:486: MPHI regs_base at 0xa087e000
[    0.705209] dwc_otg 3f980000.usb: DWC OTG Controller
[    0.705244] dwc_otg 3f980000.usb: new USB bus registered, assigned bus number 1
[    0.705280] dwc_otg 3f980000.usb: irq 62, io mem 0x00000000
[    0.705330] Init: Port Power? op_state=1
[    0.705338] Init: Power Port (0)
[    0.705546] usb usb1: New USB device found, idVendor=1d6b, idProduct=0002
[    0.705561] usb usb1: New USB device strings: Mfr=3, Product=2, SerialNumber=1
[    0.705574] usb usb1: Product: DWC OTG Controller
[    0.705585] usb usb1: Manufacturer: Linux 4.14.39 dwc_otg_hcd
[    0.705597] usb usb1: SerialNumber: 3f980000.usb
[    0.706152] hub 1-0:1.0: USB hub found
[    0.706196] hub 1-0:1.0: 1 port detected
[    0.706694] dwc_otg: FIQ enabled
[    0.706699] dwc_otg: NAK holdoff enabled
[    0.706703] dwc_otg: FIQ split-transaction FSM enabled
[    0.706714] Module dwc_common_port init
[    0.706932] usbcore: registered new interface driver usb-storage
[    0.707097] mousedev: PS/2 mouse device common for all mice
[    0.707174] IR NEC protocol handler initialized
[    0.707183] IR RC5(x/sz) protocol handler initialized
[    0.707192] IR RC6 protocol handler initialized
[    0.707201] IR JVC protocol handler initialized
[    0.707209] IR Sony protocol handler initialized
[    0.707218] IR SANYO protocol handler initialized
[    0.707226] IR Sharp protocol handler initialized
[    0.707235] IR MCE Keyboard/mouse protocol handler initialized
[    0.707244] IR XMP protocol handler initialized
[    0.707923] bcm2835-wdt 3f100000.watchdog: Broadcom BCM2835 watchdog timer
[    0.708184] bcm2835-cpufreq: min=600000 max=1200000
[    0.708572] sdhci: Secure Digital Host Controller Interface driver
[    0.708582] sdhci: Copyright(c) Pierre Ossman
[    0.708934] mmc-bcm2835 3f300000.mmc: could not get clk, deferring probe
[    0.709260] sdhost-bcm2835 3f202000.mmc: could not get clk, deferring probe
[    0.709357] sdhci-pltfm: SDHCI platform and OF driver helper
[    0.712412] ledtrig-cpu: registered to indicate activity on CPUs
[    0.712507] hidraw: raw HID events driver (C) Jiri Kosina
[    0.712590] usbcore: registered new interface driver usbhid
[    0.712595] usbhid: USB HID core driver
[    0.713001] vchiq: vchiq_init_state: slot_zero = 9f580000, is_master = 0
[    0.713906] [vc_sm_connected_init]: start
[    0.720957] [vc_sm_connected_init]: end - returning 0
[    0.721332] nf_conntrack version 0.5.0 (8192 buckets, 32768 max)
[    0.721705] ip_tables: (C) 2000-2006 Netfilter Core Team
[    0.722019] Initializing XFRM netlink socket
[    0.722304] NET: Registered protocol family 10
[    0.722868] Segment Routing with IPv6
[    0.722910] NET: Registered protocol family 17
[    0.722936] bridge: filtering via arp/ip/ip6tables is no longer available by default. Update your scripts to load br_netfilter if you need this.
[    0.722983] Key type dns_resolver registered
[    0.723160] Registering SWP/SWPB emulation handler
[    0.723489] registered taskstats version 1
[    0.726688] uart-pl011 3f201000.serial: cts_event_workaround enabled
[    0.726735] 3f201000.serial: ttyAMA0 at MMIO 0x3f201000 (irq = 87, base_baud = 0) is a PL011 rev2
[    0.727673] mmc-bcm2835 3f300000.mmc: mmc_debug:0 mmc_debug2:0
[    0.727680] mmc-bcm2835 3f300000.mmc: DMA channel allocated
[    0.781955] sdhost: log_buf @ 9f507000 (df507000)
[    0.818370] mmc1: queuing unknown CIS tuple 0x80 (2 bytes)
[    0.819946] mmc1: queuing unknown CIS tuple 0x80 (3 bytes)
[    0.821526] mmc1: queuing unknown CIS tuple 0x80 (3 bytes)
[    0.824320] mmc1: queuing unknown CIS tuple 0x80 (7 bytes)
[    0.861320] mmc0: sdhost-bcm2835 loaded - DMA enabled (>1)
[    0.862326] of_cfs_init
[    0.862409] of_cfs_init: OK
[    0.862689] Warning: unable to open an initial console.
[    0.877411] Freeing unused kernel memory: 8192K
[    0.915282] random: fast init done
[    0.921523] Indeed it is in host mode hprt0 = 00021501
[    1.018274] mmc1: new high speed SDIO card at address 0001
[    1.051752] mmc0: host does not support reading read-only switch, assuming write-enable
[    1.055407] mmc0: new high speed SDHC card at address aaaa
[    1.056197] mmcblk0: mmc0:aaaa SB16G 14.8 GiB
[    1.060411]  mmcblk0: p1 p2 p3 p4 < p5 p6 >
[    1.131412] usb 1-1: new high-speed USB device number 2 using dwc_otg
[    1.131617] Indeed it is in host mode hprt0 = 00001101
[    1.314645] udevd[237]: starting version 237
[    1.371701] usb 1-1: New USB device found, idVendor=0424, idProduct=9514
[    1.371723] usb 1-1: New USB device strings: Mfr=0, Product=0, SerialNumber=0
[    1.372392] hub 1-1:1.0: USB hub found
[    1.372490] hub 1-1:1.0: 5 ports detected
[    1.691381] usb 1-1.1: new high-speed USB device number 3 using dwc_otg
[    1.821936] usb 1-1.1: New USB device found, idVendor=0424, idProduct=ec00
[    1.821960] usb 1-1.1: New USB device strings: Mfr=0, Product=0, SerialNumber=0
[    1.824888] smsc95xx v1.0.6
[    1.917672] smsc95xx 1-1.1:1.0 eth0: register 'smsc95xx' at usb-3f980000.usb-1.1, smsc95xx USB 2.0 Ethernet, b8:27:eb:bb:7a:cc
[    2.071435] Under-voltage detected! (0x00050005)
[    2.662022] EXT4-fs (mmcblk0p2): mounted filesystem with ordered data mode. Opts: (null)
[    2.766405] EXT4-fs (mmcblk0p5): mounted filesystem with ordered data mode. Opts: (null)
[    3.154966] EXT4-fs (mmcblk0p2): re-mounted. Opts: (null)
[    3.164553] aufs au_opts_verify:1623:init[1]: dirperm1 breaks the protection by the permission bits on the lower branch
[    3.557764] systemd[1]: System time before build time, advancing clock.
[    3.585032] systemd[1]: systemd 237 running in system mode. (-PAM -AUDIT -SELINUX +IMA -APPARMOR +SMACK +SYSVINIT +UTMP -LIBCRYPTSETUP -GCRYPT -GNUTLS +ACL +XZ -LZ4 -SECCOMP +BLKID -ELFUTILS +KMOD -IDN2 -IDN -PCRE2 default-hierarchy=hybrid)
[    3.585610] systemd[1]: Detected architecture arm.
[    3.591823] systemd[1]: No hostname configured.
[    3.591864] systemd[1]: Set hostname to <localhost>.
[    3.600209] systemd[1]: Hardware watchdog 'Broadcom BCM2835 Watchdog timer', version 0
[    3.600256] systemd[1]: Set hardware watchdog to 10s.
[    3.696086] systemd[1]: File /lib/systemd/system/systemd-journald.service:35 configures an IP firewall (IPAddressDeny=any), but thelocal system does not support BPF/cgroup based firewalling.
[    3.696121] systemd[1]: Proceeding WITHOUT firewalling in effect! (This warning is only shown for the first loaded unit using IP firewalling.)
[    4.013105] systemd[1]: Unnecessary job for /dev/disk/by-label/resin-rootA was removed.
[    4.013161] systemd[1]: Unnecessary job for /dev/disk/by-label/resin-state was removed.
[    4.018768] random: systemd: uninitialized urandom read (16 bytes read)
[    4.019241] random: systemd: uninitialized urandom read (16 bytes read)
[    4.019408] random: systemd: uninitialized urandom read (16 bytes read)
[    4.897936] i2c-gpio i2c@0: using pins 10 (SDA) and 11 (SCL)
[    5.057564] snd_bcm2835: module is from the staging directory, the quality is unknown, you have been warned.
[    5.060258] bcm2835_alsa bcm2835_alsa: card created with 8 channels
[    5.539621] brcmfmac: F1 signature read @0x18000000=0x1541a9a6
[    5.552221] brcmfmac: brcmf_fw_map_chip_to_name: using brcm/brcmfmac43430-sdio.bin for chip 0x00a9a6(43430) rev 0x000001
[    5.552527] usbcore: registered new interface driver brcmfmac
[    5.670862] EXT4-fs (mmcblk0p6): mounted filesystem with ordered data mode. Opts: (null)
[    5.785193] brcmfmac: brcmf_c_preinit_dcmds: Firmware version = wl0: Oct 23 2017 03:55:53 version 7.45.98.38 (r674442 CY) FWID 01-e58d219f
[    5.785976] brcmfmac: brcmf_c_preinit_dcmds: CLM version = API: 12.2 Data: 7.11.15 Compiler: 1.24.2 ClmImport: 1.24.1 Creation: 2014-05-26 10:53:55 Inc Data: 9.10.39 Inc Compiler: 1.29.4 Inc ClmImport: 1.36.3 Creation: 2017-10-23 03:47:14
[    6.371162] EXT4-fs (mmcblk0p3): mounted filesystem with ordered data mode. Opts: (null)
[    7.543753] uart-pl011 3f201000.serial: no DMA platform data
[    8.318170] random: crng init done
[    8.318190] random: 7 urandom warning(s) missed due to ratelimiting
[    8.678991] i2c /dev entries driver
[    8.701634] brcmfmac: power management disabled
[    9.896317] IPv6: ADDRCONF(NETDEV_UP): eth0: link is not ready
[    9.994121] smsc95xx 1-1.1:1.0 eth0: hardware isn't capable of remote wakeup
[    9.994572] IPv6: ADDRCONF(NETDEV_UP): eth0: link is not ready
[   10.115299] IPv6: ADDRCONF(NETDEV_UP): wlan0: link is not ready
[   10.161085] IPv6: ADDRCONF(NETDEV_UP): wlan0: link is not ready
[   10.161638] brcmfmac: power management disabled
[   10.700720] IPv6: ADDRCONF(NETDEV_UP): wlan0: link is not ready
[   10.700780] brcmfmac: power management disabled
[   10.975313] IPv6: ADDRCONF(NETDEV_UP): wlan0: link is not ready
[   11.346105] Netfilter messages via NETLINK v0.30.
[   11.352319] ctnetlink v0.93: registering with nfnetlink.
[   11.361824] IPv6: ADDRCONF(NETDEV_UP): balena0: link is not ready
[   12.197068] IPv6: ADDRCONF(NETDEV_UP): wlan0: link is not ready
[   12.197116] brcmfmac: power management disabled
[   12.208821] Bridge firewalling registered
[   12.245766] Bluetooth: Core ver 2.22
[   12.245882] NET: Registered protocol family 31
[   12.245893] Bluetooth: HCI device and connection manager initialized
[   12.245926] Bluetooth: HCI socket layer initialized
[   12.245946] Bluetooth: L2CAP socket layer initialized
[   12.245988] Bluetooth: SCO socket layer initialized
[   12.267740] Bluetooth: HCI UART driver ver 2.3
[   12.267763] Bluetooth: HCI UART protocol H4 registered
[   12.267775] Bluetooth: HCI UART protocol Three-wire (H5) registered
[   12.268012] Bluetooth: HCI UART protocol Broadcom registered
[   12.660502] Bluetooth: BNEP (Ethernet Emulation) ver 1.3
[   12.660529] Bluetooth: BNEP filters: protocol multicast
[   12.660564] Bluetooth: BNEP socket layer initialized
[   13.493669] IPv6: ADDRCONF(NETDEV_CHANGE): wlan0: link becomes ready
[   13.944495] IPv6: ADDRCONF(NETDEV_UP): supervisor0: link is not ready
[   15.129244] IPv6: ADDRCONF(NETDEV_UP): br-4b9a0ab1dd4a: link is not ready
[   21.092994] systemd-udevd[56]: starting version 215
[   21.201099] systemd-journald[49]: Received request to flush runtime journal from PID 1
[   38.869329] IPv6: ADDRCONF(NETDEV_UP): supervisor0: link is not ready
[   43.671401] Voltage normalised (0x00000000)
[   51.991422] Under-voltage detected! (0x00050005)
[   56.151367] Voltage normalised (0x00000000)
[   66.551349] Under-voltage detected! (0x00050005)
[   72.791337] Voltage normalised (0x00000000)

**Comment by drewcovi** [comment]
@floion gonna try now with an older OS version... cant imagine what else is going wrong

**Comment by drewcovi** [comment]
No dice 😢

**Comment by shaunmulligan** [comment]
@drewcovi I assume the `dtoverlay=hyperpixel,hyperpixel-gpio-backlight` is not in resinOS default dtoverlays, is it included in the default set on raspbian yet? When I looked at it initially it always required manually copying that dtb into the `boot/overlays`

**Comment by drewcovi** [comment]
@shaunmulligan you're 10% correct.

any reason custom overlays couldn't be somehow added to an application for preload?

**Comment by shaunmulligan** [comment]
@drewcovi we can, but the problem we need to figure out is how to include them on hostOS updates too, as currently the overlays get updated with OS updates and we want to maintain that behaviour. We have some ideas on how to do this, but its still in the works. In the meantime i might try just get the hyperpixel4 dtb included in https://github.com/balena-os/balena-raspberrypi :)

**Comment by dfranssen** [comment]
Not sure if it is relevant here, but after spending several hours getting the **touch** working for my hyperpixel**4** on a rpi3, it might be worth mentioning it somewhere :-)

In short: load the `goodix` driver with modprobe

Detailed version:
1. I also copied the `hyperpixel4.dtbo` to the `/boot/overlays` folder of the SD card flashed with balena-os (I built it from [source](https://github.com/pimoroni/hyperpixel4/tree/master/src) on a rpi3 with raspbian stretch lite, scp-ed it to my local machine and copied it to the other SD card)
2. configure the fleet variables in balenaCloud according the [CONFIG_LINES](https://github.com/pimoroni/hyperpixel4/blob/master/install.sh)
3. my docker is extending from `balenalib/%%BALENA_MACHINE_NAME%%-node:8` in order to run an electron/vuejs app via X11. I also copied the [hyperpixel4-init](https://github.com/pimoroni/hyperpixel4/blob/master/dist/hyperpixel4-init) to `/usr/bin/hyperpixel4-init` in the image. A running container will execute `CMD ["bash", "/usr/src/app/start.sh"]`
4.  the `start.sh` begins with `modprobe i2c-dev && modprobe goodix && /usr/bin/hyperpixel4-init`

@shaunmulligan @spanceac if it is relevant, the info could perhaps be added in the [documentation](https://www.balena.io/docs/learn/develop/hardware/i2c-and-spi) somewhere?

**Comment by petrosagg** [comment]
@shaunmulligan @floion can we include the hyperpixel overlay to our images? It looks pretty popular

**Comment by floion** [comment]
https://github.com/balena-os/balena-raspberrypi/pull/400

**Comment by floion** [comment]
@shaunmulligan @petrosagg which ones to add? hyperpixel https://github.com/pimoroni/hyperpixel , hyperpixel4 https://github.com/pimoroni/hyperpixel4/ or both?

If for hyperpixel 4, for which combination as detailed in https://github.com/pimoroni/hyperpixel4/#manual-installation ?

**Comment by shaunmulligan** [comment]
Hmm, @floion i think we should do the hyperpixel4, i wonder if their is a nice way to just have all four options with different names? some thing like:
- `hyperpixel4-pi3`
- `hyperpixel4-pi4`
- `hyperpixel4-square-pi3`
- `hyperpixel4-square-pi4`

Would that work?

**Comment by floion** [comment]
Sure. Let's do it like that

**Comment by floion** [comment]
Done in https://github.com/balena-os/balena-raspberrypi/pull/400 so closing this item
