### ISSUE TITLE
Adding udev rule for ZTE 3630

### ISSUE THREAD

**Issue by joehounsham** [balena-os/balena-raspberrypi#245]
Customer ( Michelin) would like the following commands to be run during boot at OS level for their LTE modem:

- modprobe option
- echo 0x19d2 0x1476 > /sys/bus/usb-serial/drivers/option1/new_id

Tested on 2.13.6

<img src="https://frontapp.com/assets/img/icons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_e0ur)

**Comment by floion** [comment]
@joehounsham guess this can be closed now as we allow people to add their own udev rules.
Confirm?
