### ISSUE TITLE
Update wifi firmware to 7.45.173 (for pi3 b+)

### ISSUE THREAD

**Issue by floion** [balena-os/balena-raspberrypi#252]
<img src="https://frontapp.com/assets/img/icons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_f6oj)

**Comment by floion** [comment]
See also https://github.com/RPi-Distro/firmware-nonfree/issues/5

**Comment by agherzan** [comment]
Recommend doing that at the BSP layer level.

**Comment by floion** [comment]
Related https://forums.balena.io/t/rpi-3-wifi-connection-unstable/3963/28

**Comment by floion** [comment]
Related https://forums.balena.io/t/rpi3-onboard-wifi-unstable-fin1-0-on-same-wifi-is-working-fine/29069

**Comment by floion** [comment]
We now have version 7.45.189
