### ISSUE TITLE
Add support for the Raspberry Pi 3 A+ board

### ISSUE THREAD

**Issue by imrehg** [balena-os/balena-raspberrypi#274]
This needs most likely 4.14.79 kernel + firmware. Accelerating it to be added to the current setup, not waiting for new yocto version.

[Flowdock convo](https://www.flowdock.com/app/rulemotion/pub/threads/7I8z6rLqeACwLsEqyka3YJhaMC4)

**Comment by Timmoz** [comment]
Any update on this? Is someone working on a RPI 3A+ support?

**Comment by floion** [comment]
Hi. The work for this has been done and merged in our staging environment. The next rpi3 release (which is due soon, a week or so, maybe less) will be compatible with the 3a+

**Comment by Timmoz** [comment]
Great. I'll wait an other week, no problem.

**Comment by Jaeyoung-Lim** [comment]
Are there any updates regarding this?

**Comment by Jaeyoung-Lim** [comment]
@floion It would be helpful if we can get a ETA to prepare, Thanks

**Comment by paulchambers** [comment]
@imrehg 2.29.0+rev1 works on a Raspberry Pi 3 A+ for me :)

    SystemTime:        2019-01-01T12:32:24.121336033Z
    KernelVersion:     4.14.79
    OperatingSystem:   balenaOS 2.29.0+rev1
    Architecture:      armv7l

**Comment by imrehg** [comment]
Support added in 2.29.0+rev1
https://github.com/balena-os/balena-raspberrypi/blob/master/CHANGELOG.md#v2290rev1
