### ISSUE TITLE
Raspberry Pi 3B+ Mac Spoofing stops IPV4 lease from router

### ISSUE THREAD

**Issue by thgreasi** [balena-os/balena-raspberrypi#298]
MAC spoofing is working properly on RPi 3B but the same process fails on RPi 3B+.
The device goes offline and isn't getting an IPV4 lease from the router any more.

The minimal nmcli command that demonstrates the different behavior on the 3B and 3B+ is:
```
export DBUS_SYSTEM_BUS_ADDRESS=unix:path=/host/run/dbus/system_bus_socket

nmcli --nocheck con mod "Wired connection 1" 802-3-ethernet.cloned-mac-address "B8:27:EB:00:00:00"
nmcli --nocheck con up "Wired connection 1"
Supervisor: 9.0.1
Host OS: balenaOS 2.29.2+rev2
VM OS: Debian Stretch
```

Dockerfile:
```
FROM resin/%%RESIN_MACHINE_NAME%%-debian:latest

RUN apt-get update && 
apt-get install network-manager && 
systemctl mask NetworkManager

ENV INITSYSTEM on
```

<img src="https://frontapp.com/assets/img/icons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_hlkr)

**Comment by floion** [comment]
This will be fixed in balenaOS 2.29.2+rev8 or newer
