### ISSUE TITLE
64 bit version for Fin CM3

### ISSUE THREAD

**Issue by mz8i** [balena-os/balena-raspberrypi#305]
Now that support has been added for RPi3 64 bit version of BalenaOS, is it possible to add the same for the Balena Fin with CM3?
The use cases are the same as for RPi3 - running MongoDB and other software not available for 32 bit platforms.
A more specific IoT-related use cases is running the EdgeX microservices platform for IoT gateways, which currently relies on Mongo and therefore does not support 32 bit architectures either.

**Comment by floion** [comment]
@shaunmulligan we should probably add this to the queue

**Comment by ebradbury** [comment]
Any update on this? Many official docker images have moved on to only supporting ARM64.

**Comment by mz8i** [comment]
Closing this old issue
