### ISSUE TITLE
Use kernel 4.9-skb for revpi-core-3

### ISSUE THREAD

**Issue by smilykoch** [balena-os/balena-raspberrypi#310]
Hi Balena.

We are using your software on a fleet of revpi-core-3, and had found a bug resulting in lots of recv timeouts. The bug was reported and fixed in the balena-revpi repo before it being archived. 

I have been promised that you will downgrade the kernel of the revpi to kunbus's 4.9-skb branch in this repo, but was wondering if you could give us a timeline on when we can expect this to happen, and also when we can expect to see a full released image including this change, for a balenaOS host update? We have a large number of costumers experiencing issues as a result of this, and would very much like to be able to hostupdate their devices remotely. This is thus a huge issue for us!

Thank you.

**Comment by smilykoch** [comment]
@floion

**Comment by floion** [comment]
Hi, looking to have this done and released sometimes next week.

**Comment by smilykoch** [comment]
Sounds great! The sooner the better, as we have a lot of affected costumers.

**Comment by smilykoch** [comment]
@floion Hi, any updates regarding this issue? Our costumers are pushing us here. Anything i can do to help?

**Comment by floion** [comment]
Hi. We need some fixes in other parts of the OS done tomorrow and then we'll do the switch to the 4.9 kernel, test and hopefully deploy in the next days. Stay tuned, will  comment here when it's done

**Comment by floion** [comment]
Created https://github.com/balena-os/balena-raspberrypi/pull/317

**Comment by smilykoch** [comment]
Great to see a PR ! Remember though, that the piControl module is also built on a kernel specific branch.

**Comment by smilykoch** [comment]
Any update on when we can expect a release of this, available through balena host update?

**Comment by floion** [comment]
It has been released internally and we are testing it. Hopefully on Tuesday it will be available

**Comment by martinjlowm** [comment]
Please make some progress! Our customers are complaining - Kind regards, Finn Hunneche, CEO Blackbird, Denmark

**Comment by floion** [comment]
We are running the internal testsuite. We discovered a problem with the hostOS update so we need to have that fixed before releasing to production.

**Comment by floion** [comment]
Version 2.31.5+rev2 has been released and contains kernel 4.9 with the realtime extension enabled
