### ISSUE TITLE
Fin WiFi driver dtparam support

### ISSUE THREAD

**Issue by majorz** [balena-os/balena-raspberrypi#312]
We need to add `__overrides__` section to our Fin overlay, so that certain settings like driver mode and debug level can be overridden through config.txt and other means.

**Comment by floion** [comment]
Fixed by https://github.com/balena-os/balena-raspberrypi/pull/377/commits/df698f4bb68edcaa8eb6236c3f9dfd88f4a4b8b7 from https://github.com/balena-os/balena-raspberrypi/pull/377/commits
