### ISSUE TITLE
Patch the Marvell WiFi power sequence driver to support the Fin WiFi module

### ISSUE THREAD

**Issue by majorz** [balena-os/balena-raspberrypi#330]
We have a number of reports for the WiFi driver not initializing correctly on boot. We narrowed this down to not employing the proper PDN sequence for the particular WiFi chipset, which the kernel does not support yet. We need to implement it in the corresponding driver.

**Comment by clongbottom** [comment]
Any ideas when this is going to be resolved?

**Comment by majorz** [comment]
We are still actively working on this. Due to some additional bugs we encountered with the related mmc/sdio kernel drivers it is taking us more time, but we are making steady progress.
