### ISSUE TITLE
Update meta-balena submodule

### ISSUE THREAD

**Issue by adolfogc** [balena-os/balena-raspberrypi#331]
#326 was recently merged, but the **meta-balena** submodule still needs to be updated to a recent version, e.g., v2.34.1; the current version is missing the **meta-balena-thud** directory.

**Comment by floion** [comment]
This will get fixed today or tomorrow the latest I hope (we are waiting for a new meta-balena release)

**Comment by adolfogc** [comment]
Ok, thanks for the info.

**Comment by floion** [comment]
This was merged today so we can close this.
