### ISSUE TITLE
Bluetooth fails on rpi0w

### ISSUE THREAD

**Issue by horia-delicoti** [balena-os/balena-raspberrypi#338]
device: `rpi0wireless`
balenaos: `2.36.0+rev2`
[Flowdock conv](https://www.flowdock.com/app/rulemotion/device-testing/threads/0BCEewDQNYDZOR57rvYc5EsxZkf?filter=search&query=alliance)

**Comment by floion** [comment]
Tested by @horia-delicoti on v2.44.0+rev1 and bt works now
