### ISSUE TITLE
Add support for Raspberry Pi 4

### ISSUE THREAD

**Issue by zrzka** [balena-os/balena-raspberrypi#344]
https://www.raspberrypi.org/products/raspberry-pi-4-model-b/

**Comment by Jaeyoung-Lim** [comment]
Hi, are there any ETAs or updates regarding support for the RPi4?

**Comment by floion** [comment]
Hi. No ETA yet. It can be in the following week, we need this https://github.com/agherzan/meta-raspberrypi/pull/437 merged first

**Comment by Jaeyoung-Lim** [comment]
@floion I can see that the https://github.com/agherzan/meta-raspberrypi/pull/437 ! I would be happy to test it out before the production release

**Comment by agherzan** [comment]
@Jaeyoung-Lim There is some more work needed. We will update this thread when it's ready for a spin.

**Comment by Jaeyoung-Lim** [comment]
@agherzan Awesome

**Comment by MHarris021** [comment]
According to the status of https://github.com/agherzan/meta-raspberrypi/pull/437 it has now been merged. I there anything else required before balena OS can support running on an rpi4?

**Comment by floion** [comment]
Hi, yes, there is an issue related to the production image not booting when `console=null` is supplied in the kernel cmdline. We are currently looking at this

**Comment by MHarris021** [comment]
> Hi, yes, there is an issue related to the production image not booting when `console=null` is supplied in the kernel cmdline. We are currently looking at this

@floion thank you for the update

**Comment by rjhuijsman** [comment]
Hi! Any updates in the last week? Any hint of an ETA?

(Sorry to be nagging, our project will get a big benefit from being able to upgrade to the Pi 4!)

**Comment by floion** [comment]
No updates yet. This is still in the working queue

**Comment by codefriar** [comment]
Looking forward to this! Thanks for your hard work Balena team!

**Comment by agherzan** [comment]
If you feel like testing some early support you can build https://github.com/balena-os/balena-raspberrypi/tree/ag/rpi4 (be aware that it's a wip branch which might get rebased).

**Comment by ollym** [comment]
@agherzan that branch hasn't been updated in 17 days. What's blocking the RPI4 branch being merged? Are there changes up-stream you're still waiting on?

**Comment by ollym** [comment]
Ok, @agherzan do you have any indication of timeline? If we're talking 1-2 weeks then we'll wait. Anything more I'll build that branch and we'll use that for a project we need to deploy. Thanks

**Comment by Jaeyoung-Lim** [comment]
@agherzan I share the same status with @ollym

**Comment by gpulido** [comment]
@agherzan I'm also in the same status as @ollym  and @Jaeyoung-Lim

**Comment by agherzan** [comment]
Hi. Good to see this interest. We are currently testing and finalising support. The optimist estimation for deploying is this week if testing reveals no major issues.

**Comment by mario7754** [comment]
Hi @agherzan. Any news regarding the merge to master branch?

**Comment by agherzan** [comment]
The support PR is up and in review.

**Comment by mario7754** [comment]
Do you expect it to be merged today?

**Comment by agherzan** [comment]
It might happen. The best way to confirm this is to follow the PR.

**Comment by greaterfool** [comment]
Well. My timing could not have been more perfect, it seems.

**Comment by mario7754** [comment]
Why isn't it merged? Is something still missing?

**Comment by JeffJassky** [comment]
After merging can we expect it show up as a device option under the "Add a new device" section of the dashboard? Or will we still have to manually build?

**Comment by floion** [comment]
Hi. Expect this to be available in the dashboard by Wednesday. I will try for Tuesday, depends on my workload

**Comment by JeffJassky** [comment]
In the meantime does anybody have a raspberrypi4 image they can share? I'm running OSX and having trouble getting Yocto/oe to build. Ideally, an image that I can add a wpa_supplicant file to.

**Comment by mario7754** [comment]
Any news @floion ?

**Comment by floion** [comment]
Hi all, balenaOS version 2.41.0+rev4 is now available for RaspberryPi 4. Enjoy!

**Comment by wlisac** [comment]
This is great - thank you! Looking forward to trying it out. 

Out of curiosity, are there any plans to support 32 bit as well like with Pi 3?

**Comment by pwt** [comment]
@wlisac : you might want to take a look at the response to my question on the Balena forum:
  https://forums.balena.io/t/building-balenaos-for-rpi4/23993

**Comment by Jaeyoung-Lim** [comment]
Works great!

**Comment by mullcom** [comment]
Some help please. I get my pi4 only to boot loop when i test this out. I dont finding any information to solving it..

**Comment by floion** [comment]
Hi, what exactly are you trying?
