### ISSUE TITLE
Use new systemd from meta-balena from v2.41

### ISSUE THREAD

**Issue by ZubairLK** [balena-os/balena-raspberrypi#367]
https://github.com/balena-os/meta-balena/pull/1622 fixed the issue for production images where they would hang due to `console=null` in kernel cmdline.

Opening an issue to keep a track of this. I'd appreciate keeping systemd in sync with meta-balena

**Comment by floion** [comment]
Fixed by https://github.com/balena-os/balena-raspberrypi/pull/369
