### ISSUE TITLE
balenaCloud Fin instructions different from documentation

### ISSUE THREAD

**Issue by dansku** [balena-os/balena-raspberrypi#386]
https://github.com/balena-os/balena-raspberrypi/blob/1f1064e1272418314549b7df06a07a67efe94d0a/fincm3.coffee
![image](https://user-images.githubusercontent.com/590207/64541162-51b57380-d319-11e9-9dc1-131e0145f846.png)

In BalenaCloud setup, it says to power the BalenaFin with barrel jack AND plug in USB.
In the BalenaFin documentation, it says to ONLY power the fin from USB when flashing. 

Fin documentation and dashboard instructions disagree on how to power the fin during flashing, balena.io/fin/1.1/docs says to only use the prg port (1) while the balenaCloud instructions mention both, see user-provided screenshots in this forum thread (2)

(1): https://github.com/balena-io/resin-site/blob/master/src/data/fin/1.1/docs/getting-started.md#flashing-the-os
(2): https://forums.balena.io/t/31491

**Comment by ntzovanis** [comment]
This is correct, for flashing the v1.0 Fin, both Jack and USB have to be connected. In case of the v1.1 Fin, only USB.

**Comment by floion** [comment]
@garethtdavies ^ see above for some nuance in the docs.

**Comment by floion** [comment]
Fixed by https://github.com/balena-os/balena-raspberrypi/pull/466
