### ISSUE TITLE
Add RaspPi Zero W to "Device Type" Dropdown List

### ISSUE THREAD

**Issue by dtischler** [balena-os/balena-raspberrypi#395]
Original Issue was logged here:  https://github.com/balena-io/resin-ui/issues/3067, 

After discussion with @thgreasi , moving to this Repo.

**Expected Behavior**
It would be nice to add the Raspberry Pi Zero W to the list of Device Types that is presented when creating a new Application. We currently list the Raspberry Pi v1 and Zero, but customer get confused and then assume we do not support the Zero W because it is not explicitly listed.

**Actual Behavior**
As described

**Steps to Reproduce the Problem**
Create Application
Dropdown menu lists the possible Device Types to choose from
Specifications
N/A

Browser:
OS:
Environment:

![Screen Shot 2019-09-16 at 12 57 30 PM](https://user-images.githubusercontent.com/18220601/65170291-358e9200-d9fd-11e9-80f9-6ffd2d5ff640.png)

**Comment by thgreasi** [comment]
Essentially this is just about changing
https://github.com/balena-os/balena-raspberrypi/blob/078b0add0345e94f27c15d98256f8c7b61b66761/raspberrypi.coffee#L8
to something like `Raspberry Pi (v1 / Zero / Zero W)` (not sure about the wording).
Let me know if this is harder that I think or has other implications (did we have any when the Pi Zero was added?).

**Comment by floion** [comment]
@shaunmulligan how shall the wording for this one be?

**Comment by shaunmulligan** [comment]
@floion the wording @thgreasi suggests looks fine to me for now
