### ISSUE TITLE
pi4 kernel too big

### ISSUE THREAD

**Issue by ZubairLK** [balena-os/balena-raspberrypi#406]
The rootfs is almost full on the pi4. Gave it a quick look. The kernel is 20megs!

A google for a raspbian pi4 kernel suggests that `kernel8-p4.img` should be 13Megs with raspbian default configs.

Maybe we aren't compressing the kernel? Maybe we enable too many options..

**Comment by alexgg** [comment]
The RPI4 already uses a compressed kernel to boot, see https://github.com/balena-os/balena-raspberrypi/commit/eafd5b4759a81b9ff638ea371df30f642242d81b
