### ISSUE TITLE
[RPI4] Boot failure with Sensehat and no HDMI (mitigated)

### ISSUE THREAD

**Issue by acostach** [balena-os/balena-raspberrypi#413]
Kernel panic occurrs when booting with a Sensehat on the PI4 and no HDMI display connected and hdmi_force_hotplug=1 NOT set in config.txt

This happens because if there's no other framebuffer for fbcon to takeover, the one created by sensehat_fb driver will be used, which is not designed this usecase.

First result seen is a kernel panic in sys_imageblit() in fb core, as soon as fbcon is notified of the sense framebuffer being registered.

We mitigated this by dropping all events regarding rpisense_fb in fbcon - https://github.com/balena-os/balena-raspberrypi/pull/412 so that no console gets bound to the rpisense fb device.

<strike>We'll raise an</strike> Raised issue https://github.com/raspberrypi/linux/issues/3300 in upstream rpi kernel to see if there's any other fix proposed for this issue. Should close current one when fix is brought in from upstream.

**Comment by floion** [comment]
https://github.com/balena-os/balena-raspberrypi/pull/412 is in production now so closing this one
