### ISSUE TITLE
gpio-ir-tx kernel module is missing

### ISSUE THREAD

**Issue by Leonti** [balena-os/balena-raspberrypi#432]
Hi!
It looks like never kernels 4.19.X don’t have `lirc-rpi` modules
They got replaced by `gpio-ir` for receiving IR and `gpio-ir-tx` for sending IR.

However `gpio-ir-tx` module is missing here:
https://github.com/balena-os/balena-raspberrypi/blob/02c73efc8ce98e45094ae62adb3347a969cd81ef/layers/meta-balena-raspberrypi/conf/layer.conf

`gpio-ir` is present though.

Would it be possible to also include `gpio-ir-tx` to the list of available overlays?

Cheers!

**Comment by floion** [comment]
Fixed by https://github.com/balena-os/balena-raspberrypi/pull/451
