### ISSUE TITLE
hdmi out of range problem

### ISSUE THREAD

**Issue by MarcoPower01** [balena-os/balena-raspberrypi#439]
my hdmi monitor disaply an out of range message when i run my raspberry pi 4

**Comment by csuich2** [comment]
@MarcoPower01 How did you end up resolving this? Some of my monitors work and others are displaying out of range.

**Comment by MarcoPower01** [comment]
I changed the monitor after it still  doesn't boot (stuck logo) I abbandoned this os. So I don't know how to resolve this, sorry
