### ISSUE TITLE
Release availability

### ISSUE THREAD

**Issue by adolfogc** [balena-os/balena-raspberrypi#477]
Hi, how long does it usually take for a new release to become available for updating a device on the field?

**Comment by floion** [comment]
Hi, we are currently updating other boards so this one will have to wait for next week I would say

**Comment by adolfogc** [comment]
Hi @floion, thanks for the info., is there an URL I can check for these dates in the future?

**Comment by floion** [comment]
Hi, you can check existing OS versions for the supported boards here: https://balena-io.github.io/balenaosversions/

**Comment by adolfogc** [comment]
Hi @floion, thanks for the link to that table. Is it be possible to use the staging version for a device running in development mode?
