### ISSUE TITLE
User wants to be notified once update to kernel 4.19.118 is available

### ISSUE THREAD

**Issue by AlidaOdendaal** [balena-os/balena-raspberrypi#497]
Relevant PR: https://github.com/balena-os/balena-raspberrypi/pull/496

**Comment by floion** [comment]
On rpi3 / balena fin

**Comment by shawaj** [comment]
Assuming this can be closed now @AlidaOdendaal @floion ?

**Comment by floion** [comment]
Yes, we are now on kernel 5.4
