### ISSUE TITLE
RPI4 support for i2c3, i2c4, i2c5, i2c6 

### ISSUE THREAD

**Issue by adamtec** [balena-os/balena-raspberrypi#519]
Raspberry PI 4 supports up to 6 I2C busses. It looks like in both 2.51.1 and 2.53.9 these DTO aren't exposed. Could this be added in near future release so I don't have to resort to i2c-gpio?

**Comment by floion** [comment]
Hi. This should be fixed by https://github.com/balena-os/balena-raspberrypi/pull/521

**Comment by apage224** [comment]
Thanks I see them now in 2.53.12

**Comment by floion** [comment]
You are welcome.
