### ISSUE TITLE
Pack the generated defconfig along prebuilt modules

### ISSUE THREAD

**Issue by acostach** [balena-os/balena-raspberrypi#551]
We could include the generated defconfig along the prebuilts for the wlan drivers in https://github.com/balena-os/balena-raspberrypi/tree/master/layers/meta-balena-raspberrypi/recipes-kernel/sd8887-mrvl/prebuilts , so that it can be re-used for custom OS builds. A similar defconfig needs to be used for the kernel to load these pre-built drivers, otherwise loading will fail due to mismatching symbol versions.

**Comment by crazystick** [comment]
Since the switch to Dunfell, the default kernel version moved to 5.4 but the sd8887 prebuilts are still for 4.19 

Would be good to get new versions and also have this issue solved, as they will be unusable without the matching config

**Comment by alexgg** [comment]
The defconfig is already available.
