### ISSUE TITLE
Support for Telit LE910C1-EUX

### ISSUE THREAD

**Issue by shawaj** [balena-os/balena-raspberrypi#579]
Telit recently introduced the ThreadX versions of their LE910 modem range (LE910C1-EUX)

This isn't supported until [5.7+ in Linux mainline](https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/log/?qt=grep&q=Le910c1-eux) but it's seemingly available in [5.4.y in RasPi](https://github.com/raspberrypi/linux/blob/rpi-5.4.y/drivers/usb/serial/option.c)

Can we pull this in to next balenaOS release for balenaFin?

Starting this issue to track support for our work with Soracom. Cc @mpous

**Comment by jakogut** [comment]
Looks like this issue can be closed now, as we ship 5.4.y on the Fin since v2.67.3+rev1.
