### ISSUE TITLE
Community user is requesting kernel 5.10 for RPI

### ISSUE THREAD

**Issue by klutchell** [balena-os/balena-raspberrypi#601]
I've asked for the exact device type JF, but I would assume pi3 for now.

The new kernel has been merged upstream in master (not dunfell).

https://github.com/agherzan/meta-raspberrypi/pull/808

**Comment by dtischler** [comment]
User is using a RaspberryPi 4, but, this would also be nice to have for the Fin, as he is receiving some of those as well.

**Comment by krasi-georgiev** [comment]
It was me who requested it and the device is Rpi4

**Comment by MTolba** [comment]
Another support [thread](https://jel.ly.fish/4c32c798-3051-445e-a3b6-46fd9cb40990) where kernel 5.10 is required to solve an issue with PCIe cards.

Resource : https://www.raspberrypi.org/forums/viewtopic.php?t=301016

**Comment by dtischler** [comment]
Another email has come in (Hello@) requesting an updated kernel, albeit for the Raspberry Pi Zero...not sure if all Pi variants use same kernel or not.
