### ISSUE TITLE
Release RaspberryPi3 to >= meta-balena v2.71.3 to include engine healtchcheck patch

### ISSUE THREAD

**Issue by alexgg** [balena-os/balena-raspberrypi#621]
From support https://jel.ly.fish/4e42fae6-dd60-45ef-891e-b2a7c744fa50

The customer is currently on rolling releases but would like to move to ESR, so once https://github.com/balena-os/meta-balena/pull/2131 is merged a new ESR release is also needed for the RPI3.

**Comment by floion** [comment]
Release `2.72.0+rev1` is available for rpi3
