### ISSUE TITLE
Release needed for Nebra HNT device type with Sv 12.4.5

### ISSUE THREAD

**Issue by acostach** [balena-os/balena-raspberrypi#630]
A new Nebra HNT release is needed for host config variables, for this the supervisor release v12.4.5 needs to be included in meta-balena.

**Comment by acostach** [comment]
Brought in meta-balena by https://github.com/balena-os/meta-balena/pull/2136

**Comment by ryanteck** [comment]
Hia @acostach ,

Do you think this is likely going to be resolved by Monday?

**Comment by acostach** [comment]
Hello @ryanteck, we're working on this as we speak. Can't promise anything but if everything goes as planned it should be solved by then.

**Comment by acostach** [comment]
Hi @ryanteck, v2.73.1+rev1 is now available in the dashboard. Let me know if the overlays issue is still present with this version.

**Comment by acostach** [comment]
Fix available in production, closing.
