### ISSUE TITLE
User is Requesting Updated Kernel for RaspPi Zero

### ISSUE THREAD

**Issue by dtischler** [balena-os/balena-raspberrypi#633]
A community user has requested an update to the RaspberryPi Zero OS, which hopefully includes a kernel version bump, to pull in this patch:  https://github.com/raspberrypi/linux/commit/b69524d02076345f03fef50d3aa4097df4be4e73#diff-5a62c2c8d1e6f6475c3825cc14977cca

Current OS build for the Pi Zero is 2.54, but I see the Pi3 is at 2.72.

**Comment by markFieldman** [comment]
It will also help to connect Zero`s to last openBalena server, so important update. Bump!

**Comment by floion** [comment]
Hi, we have released OS version v2.83.21+rev1 for the RPI Zero which has an updated kernel.
