### ISSUE TITLE
Customer in need of BlueZ update from meta-balena

### ISSUE THREAD

**Issue by kenna-smith** [balena-os/balena-raspberrypi#670]
Customer's deployment is held up waiting for [this update](https://github.com/balena-os/balena-raspberrypi/blob/master/CHANGELOG.md#2021-06-02-1):

(2021-05-26)
bluez5: Use bluez5 recipe from poky master [Zahari Petkov]

**Comment by acostach** [comment]
Hi @kenna-smith, BalenaOS v2.80.3+rev1 is now available for Pi4 in production dashboard.
