### ISSUE TITLE
User requesting firmware 1.20210527 for raspberryp4-64

### ISSUE THREAD

**Issue by klutchell** [balena-os/balena-raspberrypi#679]
In order to avoid this issue: https://github.com/raspberrypi/firmware/issues/1552

> we ran into a number of problems with the firmware you're currently shipping in your balena-os-images (for example screen blanking on accelerated video playback), so upgrading to https://github.com/raspberrypi/firmware/releases/tag/1.20210527 might be a good idea

**Comment by floion** [comment]
This should be fixed now in latest OS release
