### ISSUE TITLE
User requesting v2.80.11 or newer for fincm3

### ISSUE THREAD

**Issue by klutchell** [balena-os/balena-raspberrypi#682]
This is the first release with supervisor v12.8.0+ as requested.

**Comment by rudylacrete** [comment]
Hi there. Any update or estimate on that? This is definitely something which is slowing down our deployment and use of Balena as we need to make the update manually.

Thanks in advance for the feedback.

**Comment by floion** [comment]
Hi. We are doing some updates at the moment and hope to be able to release a new version sometime next week

**Comment by rudylacrete** [comment]
Hi. Do you have any update regarding next release? Thank you.

**Comment by rudylacrete** [comment]
?

**Comment by bnativel97400** [comment]
Hi. Do you some date about new balenaOS version with last supervisor version ?

**Comment by bnativel97400** [comment]
Hey. Do you have news about next balenaOS version for fincm3 ?

**Comment by floion** [comment]
Hi, sorry for the delay, we should have a new release tomorrow

**Comment by floion** [comment]
Hi, we have release OS version `v2.83.21+rev1` for the Balena Fin
