### ISSUE TITLE
Device tree overlays not working in >= 2.82.10+rev1 for aarch64 device types

### ISSUE THREAD

**Issue by danthegoodman1** [balena-os/balena-raspberrypi#695]
Certain USB GPS modules that had worked in 2.80.5+rev1 no longer are detected by the OS in 2.82.

Downgrading is a current work around.

See forum thread: https://forums.balena.io/t/usb-problem-with-rpi4-balenaos-2-82-10-rev1/343721

**Comment by terehov** [comment]
I literally just spend some hours trying to figure out what broke our USB devices and replaced a Raspi already. Any update on this? A downgrade feature would quite handy in such a case.

**Comment by zikann** [comment]
The same issue on my device. Rpi4 8GB Serial Device and Keyboard not detected.

**Comment by floion** [comment]
There is a problem with applying any overlay on 64 bits kernel `5.10.31` or newer. We'll be looking into this and will update this thread when there's progress.

**Comment by floion** [comment]
Fixed by https://github.com/balena-os/balena-raspberrypi/pull/697

**Comment by floion** [comment]
This is now fixed in `2.83.10+rev1` or newer
