### ISSUE TITLE
Development Raspberry Pi 4 image coming out as production

### ISSUE THREAD

**Issue by luandro** [balena-os/balena-raspberrypi#716]
After downloading and burning the [raspberrypi4-64&version=2.85.2+rev3.dev](https://api.balena-cloud.com/download?deviceType=raspberrypi4-64&version=2.85.2+rev3.dev&fileType=.zip&d_id=118af6d8-702e-434b-af62-991fda1717faR) image, it comes out as a production image.

**Comment by alexgg** [comment]
Unmanaged images downloaded with the latest version of the CLI, or from the `balena.io/os` webpage are now configured on the fly for the required mode.
