### ISSUE TITLE
Request for v2.87.16+rev3 or later for cm4-ioboard and pi400

### ISSUE THREAD

**Issue by klutchell** [balena-os/balena-raspberrypi#741]
We can close this issue when this PR is in production: https://github.com/balena-os/balena-raspberrypi/pull/729

cc @keenanjohnson

**Comment by keenanjohnson** [comment]
Thanks!

**Comment by acostach** [comment]
Hi @keenanjohnson, as per your comment in this PR: https://github.com/balena-os/balena-raspberrypi/pull/729#issue-1052427898 , wanted to let you know the new image v2.88.4 is now available in the dashboard for the CM4 IOBoard

**Comment by keenanjohnson** [comment]
Excellent! Thank you!
