### ISSUE TITLE
User request for v2.88 or newer for Raspberry Pi 3

### ISSUE THREAD

**Issue by lmbarros** [balena-os/balena-raspberrypi#750]
Specifically, they are interested in the "systemd/timeinit: add HTTPS time synchronisation service" feature added to 2.88.

**Comment by pipex** [comment]
Linking this to a user request for v2.87.26 or newer for Raspberry Pi 3. User is interested in fsck functionality.

**Comment by cywang117** [comment]
Linking to a user request for 2.88.10 or newer for a NetworkManager fix.

**Comment by maggie0002** [comment]
Also looking for 2.88.13 or up for the fix to the development images incorrectly changing to production: https://forums.balena.io/t/balena-raspberry-pi-os-dev-is-actually-a-prod-versions/349857/35

**Comment by floion** [comment]
`2.94.4` has now been released for this device type
