### ISSUE TITLE
Revolution Pi Connect + CAN interface

### ISSUE THREAD

**Issue by adolfogc** [balena-os/balena-raspberrypi#761]
Hi, does the Revolution Pi Connect image supports using of the CAN interface module?

**Comment by floion** [comment]
Hi, we have not tested this module but feel free to try it and if it does not work we can work out the issues if any.

**Comment by adolfogc** [comment]
Hi, it seems that one needs to configure the device by running:

```bash
revpi-config enable revpi-con-can
```

See: https://revolutionpi.com/tutorials/uebersicht-revpi-connect/revpi-con-module-anschliessen-connect/

I haven't found the source code for the `revpi-config` utility.

**Comment by adolfogc** [comment]
Related thread in RevPi's forum: https://revolutionpi.de/forum/viewtopic.php?f=6&t=3264

**Comment by adolfogc** [comment]
revpi-config: https://gist.github.com/adolfogc/b43ef6f69cb32688c01972f8e6d44937

**Comment by adolfogc** [comment]
Source for the `revpi-con-can.dtbo` overlay extracted from the buster image by Kunbus: https://revolutionpi.de/download/10448/

```
/dts-v1/;

/ {
	compatible = "brcm,bcm2837";

	fragment@0 {
		target = <0xffffffff>;

		__overlay__ {
			status = "disabled";
		};
	};

	fragment@1 {
		target-path = "/clocks";

		__overlay__ {

			can0_osc {
				compatible = "fixed-clock";
				#clock-cells = <0x00>;
				clock-frequency = <0x1e84800>;
				phandle = <0x01>;
			};
		};
	};

	fragment@2 {
		target = <0xffffffff>;

		__overlay__ {
			#address-cells = <0x01>;
			#size-cells = <0x00>;

			can@0 {
				compatible = "holt,hi3110";
				reg = <0x00>;
				spi-max-frequency = <0x989680>;
				clocks = <0x01>;
				interrupt-parent = <0xffffffff>;
				#interrupt-cells = <0x02>;
				interrupts = <0x1c 0x04>;
				status = "okay";
			};
		};
	};

	__symbols__ {
		can0_osc = "/fragment@1/__overlay__/can0_osc";
	};

	__fixups__ {
		spidev0 = "/fragment@0:target:0";
		spi0 = "/fragment@2:target:0";
		gpio = "/fragment@2/__overlay__/can@0:interrupt-parent:0";
	};

	__local_fixups__ {

		fragment@2 {

			__overlay__ {

				can@0 {
					clocks = <0x00>;
				};
			};
		};
	};
};
```

**Comment by adolfogc** [comment]
@floion The overlay referenced above needs to be added to allow using the Revpi's CAN hardware module.

**Comment by hugzerdizer** [comment]
Hello,

I'm trying to connect the CON CAN module with RevPI connect and enable it using balena. I understand that CAN overlay needs to be added to the Balena image but how do we do that. May you describe steps to follow for this application ?

Best regards,

Hugo

**Comment by acostach** [comment]
Hi @hugzerdizer , it looks like it's been included in https://github.com/balena-os/balena-raspberrypi/pull/777 , can you give it a try by setting this overlay in the dashboard configuration panel? See https://docs.balena.io/reference/OS/advanced/#setting-device-tree-overlays-dtoverlay-and-parameters-dtparam and the overlay name to set in the panel would be [revpi-connect-can.dtbo](https://github.com/balena-os/balena-raspberrypi/pull/777/commits/cfbf0e7b0450c0bc297cd9abe440d24b382bec4a#diff-a0273d9c0eba83720368710baad3a4b5b04feb5cd106abf82abfcbbf3a5fececR10)

**Comment by hugzerdizer** [comment]
Thank you for your answer @acostach ! I'm sorry I'm pretty new about these things. Can you tell me if my understanding of what we have to do is: 
-connect the RevPI via USB to my laptop.
-access the config.txt file in the image of the RevPI.
-add the line: "dtoverlay=revpi-connect-can" (no matter where)

**Comment by adolfogc** [comment]
Hi,

It's been some time since I last worked with this device, but something like the following should work:
```
dtparam=i2c_arm=on
dtparam=spi=on
disable_splash=1
avoid_warnings=1
dtparam=audio=on
dtoverlay=revpi-connect
dtoverlay=revpi-connect-can
```

Also, in case it helps, other stuff you can do, like petting the watchdog, you can do with the `revpimodio2` Python package. If I recall correctly, you need to generate a `config.rsc` file (please look into RevPi's documentation on how to do this, you need their Raspbian-based image) and place it in your container at this path `/opt/KUNBUS/config.rsc`. This will tell the RevPi which addons you have in your set-up.

Hope this helps.

**Comment by acostach** [comment]
@hugzerdizer the device-tree overlay configuration can be changed at runtime in the balena-cloud dashboard. Navigate to the device in the admin panel, select "Device-configuration" on the left and on the right panel you should see a textbox where you can add dtoverlay elements
