### ISSUE TITLE
Request for v2.89.3 or above with the switch to `vc4-kms-v3d`

### ISSUE THREAD

**Issue by alexgg** [balena-os/balena-raspberrypi#785]
On v5.10 kernels the current `vc4-fms-v3d` version fails to bring up VC4. See https://github.com/agherzan/meta-raspberrypi/commit/a6fa6b3aec36b92c3750852dd6788af9d2ce08f6.

**Comment by rahul-thakoor** [comment]
This commit breaks `vc4-fkms-v4d` on v2.88.4

https://github.com/raspberrypi/linux/commit/9e87248154a633b18b4900ee742d9894b49e019b

```
5.10.31-v8 @ balenaOS 2.85.2+rev3 works
5.10.78-v8 @ balenaOS 2.88.4 does not
```
overlay_map now expects `vc4-fkms-v3d-pi4` to be present which we do not ship in balenaOS releases >=2.88.4

**Comment by acostach** [comment]
v2.91.1 has been released for CM4
