### ISSUE TITLE
Request: Release for UniPi Neuron including balenaEngine 20.10.16

### ISSUE THREAD

**Issue by lmbarros** [balena-os/balena-raspberrypi#828]
For context, we currently have a [PR open](https://github.com/balena-os/meta-balena/pull/2583) (but not merged yet) to upgrade meta-balena for this balenaEngine version.

**Comment by lmbarros** [comment]
The PR is merged and available since balenaOS v2.97.0, we can proceed with the release now.

**Comment by floion** [comment]
OS release available in production now
