### ISSUE TITLE
tests: os: Rpi3 fails tests with connection loss / not coming back after reboots

### ISSUE THREAD

**Issue by rcooke-warwick** [balena-os/balena-raspberrypi#838]
https://jenkins.product-os.io/job/leviathan-v2-template/755/artifact/reports/worker-27718d4-os-raspberrypi3-RPi_3%20B.log
https://jenkins.product-os.io/job/leviathan-v2-template/738/artifact/reports/worker-27718d4-os-raspberrypi3-RPi_3%20B.log

**Comment by klutchell** [comment]
Closing for now!
