### ISSUE TITLE
Orange Pi Zero LTS not booting

### ISSUE THREAD

**Issue by jdohn15** [balena-os/balena-raspberrypi#884]
Hello,

I have tested multiple sd cards, and multiple Orange Pi Zero LTS, yet every time the devices will not boot and has 4 red blinks from the led and a solid green led.

edit: so the Pi will work if I boot with an ssd password and name, without ethernet plugged in. However, if ethernet is plugged in, it wont boot and the above mentioned error occurs.

**Comment by floion** [comment]
This repository is for Raspberry Pi and not related to Orange Pi boards so closing the issue.

The repository for Allwinner based boards we support is https://github.com/balena-os/balena-allwinner
