### ISSUE TITLE
Update to Yocto Kirkstone LTS

### ISSUE THREAD

**Issue by iayanpahwa** [balena-os/balena-raspberrypi#890]
Poky on Kirkstone also ships with linux-yocto 5.15 which is required by some of our ARM customers to make newer hardware work.

A noticeable driver request : rs485

**Comment by alexgg** [comment]
Depends-on: https://github.com/balena-os/meta-balena/pull/2735

**Comment by floion** [comment]
We updated to kirkstone a while back so closing this issue
