### ISSUE TITLE
Request for a release for `raspberrypi3-unipi-neuron` with v2.101.3 or above

### ISSUE THREAD

**Issue by pipex** [balena-os/balena-raspberrypi#908]
The latest version for the device type is `v2.100.0` which has a supervisor 14.0.10 which has been invalidated due to the versioning getting out of sync between the supervisor repository and the released images.

**Comment by pascal-buchs** [comment]
When can we expect this release to be available?

**Comment by floion** [comment]
Latest OS version for this device type is `2.112.8` so closing this issue.
