### ISSUE TITLE
raspberry pi 0 fails to create files in a volume during hup suite

### ISSUE THREAD

**Issue by rcooke-warwick** [balena-os/balena-raspberrypi#929]
In the hup suite, a volume is created and populated with a file, to check that volumes persist across Hups - in the pi 0's case, there is an error thrown while trying to create a file in this created volume: https://github.com/balena-os/meta-balena/blob/master/tests/suites/hup/tests/smoke.js#L51

```
not ok 2 - "balena run -v hello-world:/the-volume --entrypoint "/bin/sh" alpine -c 'echo "Howdy!" > /the-volume/the-file.txt' &&     balena run -v hello-world:/the-volume --entrypoint "/bin/sh" alpine -c 'md5sum /the-volume/the-file.txt > /the-volume/MD5.SUM'" failed. stderr: , stdout: , code: 139
```

**Comment by klutchell** [comment]
There was a bug in the old releases of balena-engine where armv5 devices like this would identify as armv7 when pulling images.
```bash
# failed
docker run alpine sh

# works
docker run arm32v6/alpine sh
# or
docker pull --platform=arm32v6 alpine
```

We should be able to workaround this by checking the architecture of the DUT and specifying the platform when pulling the alpine image. Or just use another method to create a volume that does not require pulling a multiarch image.
