### ISSUE TITLE
Cloud builders cannot build Rust projects anymore. Cargo network errors.

### ISSUE THREAD

**Issue by ragnese** [balena-os/balena-raspberrypi#997]
Very recently, I've been unable to deploy my project because it uses Rust and Cargo to build the binaries. It seems that something about the cloud ARM builders has changed to cause network issues for Cargo being able to pull dependencies.

You can't even build the Rust "Hello World" project anymore: https://github.com/balena-io-examples/balena-rust-hello-world

Just clone that repo and try to do a `balena push` and it will fail with errors like:

> [balena-hello-world]     Updating
> [balena-hello-world]   crates.io index
> [balena-hello-world]  
> [balena-hello-world]  warning
> [balena-hello-world]  : 
> [balena-hello-world]  spurious network error (2 tries remaining): could not read directory '/usr/local/cargo/registry/index/github.com-1285ae84e5963aae/.git/refs': Value too large for defined data type; class=Os (2)
> [balena-hello-world]  
> [balena-hello-world]  warning: spurious network error (1 tries remaining): could not read directory '/usr/local/cargo/registry/index/github.com-1285ae84e5963aae/.git/refs': Value too large for defined data type; class=Os (2)
> [balena-hello-world]  
> [balena-hello-world]  error: failed to get `tokio` as a dependency of package `balena-rust-hello-world v1.0.3 (/usr/src/balena-rust-hello-world)`
> [balena-hello-world]  
> [balena-hello-world]  
> [balena-hello-world]  Caused by:
> [balena-hello-world]  
> [balena-hello-world]    failed to load source for dependency `tokio`
> [balena-hello-world]  
> [balena-hello-world]  
> [balena-hello-world]  Caused by:
> [balena-hello-world]  
> [balena-hello-world]    Unable to update registry `crates-io`
> [balena-hello-world]  Caused by:
> [balena-hello-world]    failed to fetch `https://github.com/rust-lang/crates.io-index`
> [balena-hello-world]  
> [balena-hello-world]  
> [balena-hello-world]  Caused by:
> [balena-hello-world]  
> [balena-hello-world]    could not read directory '/usr/local/cargo/registry/index/github.com-1285ae84e5963aae/.git/refs': Value too large for defined data type; class=Os (2)

**Comment by floion** [comment]
Hi, this issue is not related to this repo.
Please open an issue in the forums as that's the proper place for the issue you signaled.
